# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Artistico' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.0.1'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'Firebase/Database'
  pod 'Firebase/AppIndexing'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Fabric'
  pod 'TwitterKit'
  pod 'TwitterCore'

  # Pods for Artistico

  target 'ArtisticoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
